# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration


[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction
body = """
{% if version %}\
    ## {{ version | trim_start_matches(pat="v") }} 更新一览({{ timestamp | date(format="%Y-%m-%d") }})
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*{{ commit.scope }}*: {% endif %}\
            {% if commit.breaking %}[**破坏性改动**] {% endif %}\
            {{ commit.message | upper_first }}\
            {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %}\
            {% if commit.remote.pr_number %} in #{{ commit.remote.pr_number }}{%- endif %}
    {% endfor %}
{% endfor %}

---

[如果你有 Mirror 酱 CDK 可以直接使用此高速下载源](https://mirrorchyan.com/zh/projects?rid=PCL2-CE&source=pcl2ce-gh-release)
你也可以直接在下方的 Assets 中下载

---

[GPG 签名公钥](https://github.com/PCL-Community/PCL2-CE/blob/dev/GPG-PUBLIC-KEY.asc)
公钥指纹 `81D9430A309B84272D518584EDF4453F0BBB862E`

"""
# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# Render body even when there are no releases to process.
render_always = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = [
    # Replace the placeholder <REPO> with a URL.
    #{ pattern = '<REPO>', replace = "https://github.com/orhun/git-cliff" },
]
# render body even when there are no releases to process
# render_always = true
# output file path
output = "CHANGELOG.md"

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# Require all commits to be conventional.
# Takes precedence over filter_unconventional.
require_conventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
    # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
    #{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
    # Check spelling of the commit message using https://github.com/crate-ci/typos.
    # If the spelling is incorrect, it will be fixed automatically.
    #{ pattern = '.*', replace_command = 'typos --write-changes -' },
]
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat|^impl", group = "<!-- 0 -->🚀 功能追加" },
    { message = "^fix", group = "<!-- 1 -->🐛 问题修复" },
    { message = "^refactor", group = "<!-- 2 -->🚜 重构" },
    { message = "^perf", group = "<!-- 4 -->⚡ 性能改进" },
    { message = "^improve|^imp", group = "<!-- 4 -->👀 优化改进" },
    { message = "^i18n", group = "<!-- 5 -->🌐 国际化" },
    { message = "^doc|^docs", group = "<!-- 5 -->📚 文档调整" },
    { message = "^style", group = "<!-- 5 -->🎨 样式调整" },
    { message = "^ci", group = "<!-- 6 -->🤖 工作流配置" },
    { message = "^test", skip = true },
    { message = "^chore\\(bump\\)", skip = true },
    { message = "^deps", skip = true },
    { message = "^chore\\(pr\\)", skip = true },
    { message = "^chore\\(pull\\)", skip = true },
    { message = "^wip|^temp|^tmp|^todo", skip = true },
    { message = "^chore", group = "<!-- 7 -->⚙️ 其他改动" },
    { message = "^revert", group = "<!-- 9 -->◀️ 回退改动" },
] # An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
# Exclude commits that are not matched by any commit parser.
filter_commits = true
# An array of link parsers for extracting external references, and turning them into URLs, using regex.
link_parsers = []
# Include only the tags that belong to the current branch.
use_branch_tags = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order releases topologically instead of chronologically.
topo_order_commits = true
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"
# Process submodules commits
recurse_submodules = false
