using System;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using PCL.Core.Minecraft.Saves;
using PCL.Core.Minecraft.Saves.Editing;
using PCL.Core.Minecraft.Saves.Exceptions;
using PCL.Core.Minecraft.Saves.Parsing;

namespace PCL.Core.Test.Minecraft;

// Generated by deepseek-v4-pro

[TestClass]
public class SaveManagerTest
{
    private string _tempRoot = null!;
    private SaveManager _saveManager = null!;

    [TestInitialize]
    public void Initialize()
    {
        _tempRoot = Path.Combine(Path.GetTempPath(), "PCLTest", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_tempRoot);
        _saveManager = new SaveManager();
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (Directory.Exists(_tempRoot))
            Directory.Delete(_tempRoot, true);
    }

    #region Nbt helpers

    private static void WriteLevelDat(string folderPath, Action<fNbt.NbtCompound> populateData)
    {
        var root = new fNbt.NbtCompound("");
        var data = new fNbt.NbtCompound("Data");
        populateData(data);
        root.Add(data);

        var nbtFile = new fNbt.NbtFile(root);
        var path = Path.Combine(folderPath, "level.dat");
        using var fs = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None);
        nbtFile.SaveToStream(fs, fNbt.NbtCompression.GZip);
    }

    #endregion

    #region Scan / Load

    [TestMethod]
    public async Task ScanSaveFoldersAsync_EmptyDirectory_ReturnsEmptyList()
    {
        var result = await _saveManager.ScanSaveFoldersAsync(_tempRoot);
        Assert.AreEqual(0, result.Count);
    }

    [TestMethod]
    public async Task ScanSaveFoldersAsync_ValidSave_ReturnsSaveInfo()
    {
        var folder = Path.Combine(_tempRoot, "MyWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "TestWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 1));
        });

        var result = await _saveManager.ScanSaveFoldersAsync(_tempRoot);

        Assert.AreEqual(1, result.Count);
        Assert.AreEqual("TestWorld", result[0].LevelName);
        Assert.AreEqual(GameMode.Creative, result[0].GameMode);
    }

    [TestMethod]
    public async Task ScanSaveFoldersAsync_SkipsNonSaveFolders()
    {
        var validFolder = Path.Combine(_tempRoot, "World1");
        var invalidFolder = Path.Combine(_tempRoot, "NotAWorld");
        Directory.CreateDirectory(validFolder);
        Directory.CreateDirectory(invalidFolder);

        WriteLevelDat(validFolder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "ValidWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        var result = await _saveManager.ScanSaveFoldersAsync(_tempRoot);
        Assert.AreEqual(1, result.Count);
    }

    [TestMethod]
    public async Task LoadSaveAsync_PreLegacySave_ReturnsCorrectInfo()
    {
        var folder = Path.Combine(_tempRoot, "PreLegacyWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "OldWorld"));
            data.Add(new fNbt.NbtLong("RandomSeed", 123456789L));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 2400L)); // 2 min
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtInt("SpawnX", 100));
            data.Add(new fNbt.NbtInt("SpawnY", 64));
            data.Add(new fNbt.NbtInt("SpawnZ", 200));
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual("OldWorld", info.LevelName);
        Assert.AreEqual(123456789L, info.Seed);
        Assert.AreEqual(GameMode.Survival, info.GameMode);
        Assert.IsNull(info.Difficulty);
        Assert.IsFalse(info.AllowCommands);
        Assert.IsNotNull(info.Spawn);
        Assert.AreEqual(100f, info.Spawn!.Value.X);
        Assert.AreEqual(64f, info.Spawn!.Value.Y);
        Assert.AreEqual(200f, info.Spawn!.Value.Z);
    }

    [TestMethod]
    public async Task LoadSaveAsync_LegacySave_ReturnsCorrectInfo()
    {
        var folder = Path.Combine(_tempRoot, "LegacyWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "LegacyWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtByte("allowCommands", 1));
            data.Add(new fNbt.NbtByte("Difficulty", 2)); // Normal
            data.Add(new fNbt.NbtByte("DifficultyLocked", 1));
            data.Add(new fNbt.NbtByte("hardcore", 0));
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual("LegacyWorld", info.LevelName);
        Assert.IsTrue(info.AllowCommands);
        Assert.AreEqual(Difficulty.Normal, info.Difficulty);
        Assert.IsTrue(info.IsDifficultyLocked);
        Assert.IsFalse(info.IsHardcore);
    }

    [TestMethod]
    public async Task LoadSaveAsync_ModernSave_ReturnsVersionInfo()
    {
        var folder = Path.Combine(_tempRoot, "ModernWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "ModernWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 1343)); // 1.12.2
            data.Add(new fNbt.NbtInt("GameType", 0));
            var version = new fNbt.NbtCompound("Version");
            version.Add(new fNbt.NbtString("Name", "1.12.2"));
            version.Add(new fNbt.NbtInt("Id", 1343));
            data.Add(version);
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual("ModernWorld", info.LevelName);
        Assert.AreEqual("1.12.2", info.VersionName);
        Assert.AreEqual(1343, info.VersionId);
    }

    [TestMethod]
    public async Task LoadSaveAsync_NextGenSave_ReadsDifficultySettings()
    {
        var folder = Path.Combine(_tempRoot, "NextGenWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "NextGenWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 4800));
            data.Add(new fNbt.NbtInt("GameType", 0));
            var ds = new fNbt.NbtCompound("difficulty_settings");
            ds.Add(new fNbt.NbtString("difficulty", "hard"));
            ds.Add(new fNbt.NbtByte("locked", 1));
            ds.Add(new fNbt.NbtByte("hardcore", 0));
            data.Add(ds);
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual(Difficulty.Hard, info.Difficulty);
        Assert.IsTrue(info.IsDifficultyLocked);
        Assert.IsFalse(info.IsHardcore);
    }

    [TestMethod]
    public async Task LoadSaveAsync_NextGenSpawnPosition_ReadsFromPosArray()
    {
        var folder = Path.Combine(_tempRoot, "NextGenSpawn");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "SpawnTest"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 4800));
            data.Add(new fNbt.NbtInt("GameType", 0));
            var spawn = new fNbt.NbtCompound("spawn");
            spawn.Add(new fNbt.NbtIntArray("pos", [256, 70, -128]));
            data.Add(spawn);
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.IsNotNull(info.Spawn);
        Assert.AreEqual(256f, info.Spawn!.Value.X);
        Assert.AreEqual(70f, info.Spawn!.Value.Y);
        Assert.AreEqual(-128f, info.Spawn!.Value.Z);
    }

    [TestMethod]
    public async Task LoadSaveAsync_HardcoreMode_ReturnsHardcoreGameMode()
    {
        var folder = Path.Combine(_tempRoot, "HardcoreWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "Hardcore"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtByte("hardcore", 1));
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual(GameMode.Hardcore, info.GameMode);
        Assert.IsTrue(info.IsHardcore);
    }

    [TestMethod]
    public async Task LoadSavesAsync_YieldsSavesOneByOne()
    {
        var folderA = Path.Combine(_tempRoot, "A");
        var folderB = Path.Combine(_tempRoot, "B");
        Directory.CreateDirectory(folderA);
        Directory.CreateDirectory(folderB);
        WriteLevelDat(folderA, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "A"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });
        WriteLevelDat(folderB, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "B"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        var names = new System.Collections.Generic.List<string>();
        await foreach (var info in _saveManager.LoadSavesAsync(_tempRoot, CancellationToken.None))
            names.Add(info.LevelName);

        Assert.AreEqual(2, names.Count);
        CollectionAssert.Contains(names, "A");
        CollectionAssert.Contains(names, "B");
    }

    [TestMethod]
    public async Task LoadSaveAsync_FallsBackToLevelDatOld()
    {
        var folder = Path.Combine(_tempRoot, "BackupOnly");
        Directory.CreateDirectory(folder);
        var path = Path.Combine(folder, "level.dat_old");
        var root = new fNbt.NbtCompound("");
        var data = new fNbt.NbtCompound("Data");
        data.Add(new fNbt.NbtString("LevelName", "BackupWorld"));
        data.Add(new fNbt.NbtLong("LastPlayed", 0));
        data.Add(new fNbt.NbtLong("Time", 0));
        data.Add(new fNbt.NbtInt("GameType", 0));
        root.Add(data);
        var nbtFile = new fNbt.NbtFile(root);
        using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None))
            nbtFile.SaveToStream(fs, fNbt.NbtCompression.GZip);

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual("BackupWorld", info.LevelName);
    }

    [TestMethod]
    public async Task LoadSaveAsync_NoLevelDat_ThrowsSaveNotFound()
    {
        var folder = Path.Combine(_tempRoot, "EmptyFolder");
        Directory.CreateDirectory(folder);

        await Assert.ThrowsExactlyAsync<SaveNotFoundException>(
            async () => await _saveManager.LoadSaveAsync(folder));
    }

    [TestMethod]
    public async Task LoadSaveAsync_CorruptedFile_ThrowsSaveCorrupted()
    {
        var folder = Path.Combine(_tempRoot, "CorruptedWorld");
        Directory.CreateDirectory(folder);
        File.WriteAllText(Path.Combine(folder, "level.dat"), "not valid gzip data");

        await Assert.ThrowsExactlyAsync<SaveCorruptedException>(
            async () => await _saveManager.LoadSaveAsync(folder));
    }

    [TestMethod]
    public async Task LoadSaveAsync_ReadsSeedFromWorldGenSettings()
    {
        var folder = Path.Combine(_tempRoot, "116World");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "ModernWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 2586)); // 1.16.5
            data.Add(new fNbt.NbtInt("GameType", 0));
            var wgs = new fNbt.NbtCompound("WorldGenSettings");
            wgs.Add(new fNbt.NbtLong("seed", 987654321L));
            data.Add(wgs);
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual(987654321L, info.Seed);
    }

    [TestMethod]
    public async Task LoadSaveAsync_SeedFallbackToRandomSeed()
    {
        var folder = Path.Combine(_tempRoot, "FallbackSeed");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "FallbackWorld"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 2586));
            data.Add(new fNbt.NbtInt("GameType", 0));
            var wgs = new fNbt.NbtCompound("WorldGenSettings");
            // no seed inside WorldGenSettings
            data.Add(wgs);
            data.Add(new fNbt.NbtLong("RandomSeed", 555555L));
        });

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual(555555L, info.Seed);
    }

    [TestMethod]
    public async Task LoadSaveAsync_NextGenExternalSeedFile()
    {
        var folder = Path.Combine(_tempRoot, "NextGenSeedFile");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "NextGenSeed"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 4800));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        // create external seed file
        var externalDir = Path.Combine(folder, "data", "minecraft");
        Directory.CreateDirectory(externalDir);
        var externalPath = Path.Combine(externalDir, "world_gen_settings.dat");
        var extRoot = new fNbt.NbtCompound("");
        var extData = new fNbt.NbtCompound("data");
        extData.Add(new fNbt.NbtLong("seed", 999888777L));
        extRoot.Add(extData);
        var extNbt = new fNbt.NbtFile(extRoot);
        using (var fs = new FileStream(externalPath, FileMode.Create, FileAccess.Write, FileShare.None))
            extNbt.SaveToStream(fs, fNbt.NbtCompression.GZip);

        var info = await _saveManager.LoadSaveAsync(folder);

        Assert.AreEqual(999888777L, info.Seed);
    }

    [TestMethod]
    public async Task LoadSaveAsync_NoMatchingParser_ThrowsSaveCorrupted()
    {
        // Use a custom factory that never matches any parser
        var factory = new SaveParserFactory(Array.Empty<ISaveParser>());
        var manager = new SaveManager(factory);

        var folder = Path.Combine(_tempRoot, "NoParserWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "NoParser"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        await Assert.ThrowsExactlyAsync<SaveCorruptedException>(
            async () => await manager.LoadSaveAsync(folder));
    }

    [TestMethod]
    public async Task LoadSavesAsync_SkipsCorruptedFolders()
    {
        var valid = Path.Combine(_tempRoot, "Valid");
        var corrupted = Path.Combine(_tempRoot, "Corrupted");
        Directory.CreateDirectory(valid);
        Directory.CreateDirectory(corrupted);
        File.WriteAllText(Path.Combine(corrupted, "level.dat"), "garbage");

        WriteLevelDat(valid, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "OnlyValid"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        var names = new System.Collections.Generic.List<string>();
        await foreach (var info in _saveManager.LoadSavesAsync(_tempRoot, CancellationToken.None))
            names.Add(info.LevelName);

        Assert.AreEqual(1, names.Count);
        Assert.AreEqual("OnlyValid", names[0]);
    }

    [TestMethod]
    public async Task ApplyChangesAsync_NoMatchingEditor_ThrowsSaveCorrupted()
    {
        var folder = Path.Combine(_tempRoot, "NoEditorWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "NoEditor"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        // Use an empty editor list so no editor matches
        var manager = new SaveManager(customEditors: Array.Empty<ISaveEditor>());
        var changes = new SaveChanges { AllowCommands = new Editable<bool>(true) };

        await Assert.ThrowsExactlyAsync<SaveCorruptedException>(
            async () => await manager.ApplyChangesAsync(folder, changes));
    }

    [TestMethod]
    public async Task ApplyChangesAsync_PreservesLevelDatOldBackup()
    {
        var folder = Path.Combine(_tempRoot, "BackupWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "BackupTest"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtByte("allowCommands", 0));
            data.Add(new fNbt.NbtByte("Difficulty", 1));
            data.Add(new fNbt.NbtByte("DifficultyLocked", 0));
        });

        var changes = new SaveChanges { AllowCommands = new Editable<bool>(true) };
        var applied = await _saveManager.ApplyChangesAsync(folder, changes);

        Assert.IsTrue(applied);
        Assert.IsTrue(File.Exists(Path.Combine(folder, "level.dat")));
        Assert.IsTrue(File.Exists(Path.Combine(folder, "level.dat_old")));
    }

    #endregion

    #region Editors

    [TestMethod]
    public async Task ApplyChangesAsync_LegacySave_UpdatesAllowCommands()
    {
        var folder = Path.Combine(_tempRoot, "EditWorld");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "EditTest"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtByte("allowCommands", 0));
            data.Add(new fNbt.NbtByte("Difficulty", 1));
            data.Add(new fNbt.NbtByte("DifficultyLocked", 0));
        });

        var changes = new SaveChanges { AllowCommands = new Editable<bool>(true) };
        var applied = await _saveManager.ApplyChangesAsync(folder, changes);

        Assert.IsTrue(applied);

        // Re-read and verify
        var info = await _saveManager.LoadSaveAsync(folder);
        Assert.IsTrue(info.AllowCommands);
    }

    [TestMethod]
    public async Task ApplyChangesAsync_LegacySave_UpdatesDifficulty()
    {
        var folder = Path.Combine(_tempRoot, "EditDifficulty");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "DiffTest"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtByte("allowCommands", 0));
            data.Add(new fNbt.NbtByte("Difficulty", 0));
            data.Add(new fNbt.NbtByte("DifficultyLocked", 0));
        });

        var changes = new SaveChanges { Difficulty = new Editable<Difficulty>(Difficulty.Hard) };
        var applied = await _saveManager.ApplyChangesAsync(folder, changes);

        Assert.IsTrue(applied);
        var info = await _saveManager.LoadSaveAsync(folder);
        Assert.AreEqual(Difficulty.Hard, info.Difficulty);
    }

    [TestMethod]
    public async Task ApplyChangesAsync_EmptyChanges_ReturnsFalse()
    {
        var folder = Path.Combine(_tempRoot, "EmptyEdit");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "NoChange"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("GameType", 0));
        });

        var applied = await _saveManager.ApplyChangesAsync(folder, default);
        Assert.IsFalse(applied);
    }

    [TestMethod]
    public async Task ApplyChangesAsync_NextGenSave_UsesStringDifficulty()
    {
        var folder = Path.Combine(_tempRoot, "NextGenEdit");
        Directory.CreateDirectory(folder);
        WriteLevelDat(folder, data =>
        {
            data.Add(new fNbt.NbtString("LevelName", "NextGenEdit"));
            data.Add(new fNbt.NbtLong("LastPlayed", 0));
            data.Add(new fNbt.NbtLong("Time", 0));
            data.Add(new fNbt.NbtInt("DataVersion", 4800));
            data.Add(new fNbt.NbtInt("GameType", 0));
            data.Add(new fNbt.NbtByte("allowCommands", 1));
            var ds = new fNbt.NbtCompound("difficulty_settings");
            ds.Add(new fNbt.NbtString("difficulty", "easy"));
            ds.Add(new fNbt.NbtByte("locked", 0));
            data.Add(ds);
        });

        var changes = new SaveChanges
        {
            Difficulty = new Editable<Difficulty>(Difficulty.Peaceful),
            LockDifficulty = new Editable<bool>(true),
        };
        var applied = await _saveManager.ApplyChangesAsync(folder, changes);

        Assert.IsTrue(applied);
        var info = await _saveManager.LoadSaveAsync(folder);
        Assert.AreEqual(Difficulty.Peaceful, info.Difficulty);
        Assert.IsTrue(info.IsDifficultyLocked);
    }

    #endregion
}
